logo: <p align="center"><img src="images/Portfolio_GithubIO.png"></p>
title: <p align="center">Diego Teixeira</p>
description:
  <p>
  Formado em Processos Gerencias, estudante de Sistemas de Informação e Pós Graduando em Ciência de Dados.
  <br><br>
  Construindo carreira na área de performance empresarial com conceitos de administração e computação moderna. Entusiasta por Data Science, programação e pela era disruptiva. 
  <br><br>
  </p>
  
  <p align="center">
  <a href="mailto:diegoteixeira1996@gmail.com" rel="nofollow noopener noreferrer"><img src = "https://img.shields.io/badge/Gmail-white?Style=flat&logo=Gmail"></a>
  <a href="https://www.linkedin.com/in/diegdtm/" target="_blank"><img src = "https://img.shields.io/badge/LinkedIn-blue?style=flat&logo=linkedin&labelColor=blue"></a>  
  <a href="https://github.com/DiegoTeixeiraMarques" target="_blank"><img src = "https://img.shields.io/badge/GitHub-black?Style=flat&logo=GitHub"></a>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
