title: Diego Teixeira # your name (or website title) here
logo: "/images/Portfolio_GithubIO.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Building career in the area of ​​business performance with concepts of administration and modern computing. 
  Enthusiastic about Data Science, programming and the disruptive era. 
  <br><br> 
  Construindo carreira na área de performance empresarial com conceitos de administração e computação moderna. Entusiasta por Data Science, programação e pela era disruptiva.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/diegdtm/">
  View My LinkedIn Profile 
  <br> 
  Ver Meu Perfil do LinkedIn</a> 
  
